"""Freeze Diagram Maker for Windows and wrap it in an installer.

Steps, in order:

1. read the name, version and author out of ``pyproject.toml``
2. draw ``packaging/icon.ico`` if it is missing
3. write the Windows version resource that gets compiled into the .exe
4. run PyInstaller against ``packaging/diagram-maker.spec`` into ``dist/``
5. check that the QtWebEngine pieces really landed in the bundle
6. start the frozen app offscreen and make sure it stays up
7. compile ``packaging/diagram-maker.iss`` into a setup program - or, when Inno
   Setup is not installed, write a portable zip and say what is missing

Usage::

    uv sync --extra packaging
    uv run python scripts/build_installer.py

Everything it writes goes to ``build/windows/`` and ``dist/``, both of which
are ignored by git.
"""

from __future__ import annotations

import argparse
import importlib.util
import os
import re
import shutil
import subprocess
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PACKAGING = ROOT / "packaging"
WORK = ROOT / "build" / "windows"
DIST = ROOT / "dist"

APP_DIR = "Diagram Maker"
APP_EXE = "Diagram Maker.exe"

ICON = PACKAGING.parent / "src" / "diagram_maker" / "icon.ico"
SPEC = PACKAGING / "diagram-maker.spec"
ISCC_SCRIPT = PACKAGING / "diagram-maker.iss"
DEFINES = WORK / "installer_defines.iss"

#: how long the frozen app has to survive before we call it healthy
GRACE_SECONDS = 12.0

#: what Windows reports when an application control policy blocks a program
BLOCKED = 4551


class BlockedByPolicy(RuntimeError):
    """Windows would not start a program this build wrote.

    Smart App Control refuses an executable it has not seen before, and every
    build writes a new one, so this is the machine's policy rather than a fault
    in the application.  The checks step aside and the installer is still made.
    """


def refused(error: OSError) -> bool:
    """Whether Windows refused to start the file, rather than the file failing."""
    return getattr(error, "winerror", None) == BLOCKED or "Application Control" in str(error)


INNO_HINT = (
    "Inno Setup 6 was not found, so only the portable build was produced.\n"
    "    winget install -e --id JRSoftware.InnoSetup\n"
    "    uv run python scripts/build_installer.py --skip-freeze"
)

VERSION_RESOURCE = """\
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers=({quad}),
    prodvers=({quad}),
    mask=0x3F,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo([
      StringTable(
        "040904B0",
        [
          StringStruct("CompanyName", "{author}"),
          StringStruct("FileDescription", "{description}"),
          StringStruct("FileVersion", "{version}"),
          StringStruct("InternalName", "diagram-maker"),
          StringStruct("LegalCopyright", "{copyright}"),
          StringStruct("OriginalFilename", "{exe}"),
          StringStruct("ProductName", "Diagram Maker"),
          StringStruct("ProductVersion", "{version}"),
        ],
      )
    ]),
    VarFileInfo([VarStruct("Translation", [1033, 1200])]),
  ],
)
"""

DEFINES_TEMPLATE = """\
; generated by scripts/build_installer.py - do not edit
#define AppVersion "{version}"
#define BundleDir "{bundle}"
#define OutDir "{out}"
#define IconFile "{icon}"
"""


class BuildError(Exception):
    """Something went wrong that the user has to fix."""


def say(message: str) -> None:
    print(message, flush=True)


def run(command: list[str], **keywords) -> subprocess.CompletedProcess:
    """Run a build step, letting its output through to the terminal."""
    keywords.setdefault("check", False)
    try:
        return subprocess.run(command, cwd=ROOT, **keywords)
    except OSError as error:
        if refused(error):
            raise BuildError(
                f"Windows refused to start {command[0]}: {error}\n"
                "an application control policy is blocking it; see the notes in "
                "the README about signing the build"
            ) from error
        raise


# ------------------------------------------------------------- preparation #


def metadata() -> dict[str, str]:
    """The bits of pyproject.toml the .exe and the installer need."""
    project = tomllib.loads((ROOT / "pyproject.toml").read_text("utf-8"))["project"]
    authors = project.get("authors") or [{}]
    return {
        "version": project["version"],
        "description": project.get("description", "Diagram Maker"),
        "author": authors[0].get("name", ""),
    }


def ensure_icon(force: bool) -> None:
    """Draw the icon, which is generated rather than checked in by hand."""
    if ICON.exists() and not force:
        return
    say(f"icon       drawing {ICON.relative_to(ROOT)}")
    if run([sys.executable, str(PACKAGING / "make_icon.py")]).returncode != 0:
        raise BuildError("could not draw the icon")


def version_quad(version: str) -> tuple[int, int, int, int]:
    """``0.1.0`` as the four integers a Windows version resource wants."""
    found = [int(part) for part in re.findall(r"\d+", version)][:4]
    return tuple((found + [0, 0, 0, 0])[:4])  # type: ignore[return-value]


def write_version_resource(info: dict[str, str]) -> Path:
    """Stamp the .exe with the version, so Explorer shows something useful."""
    quad = version_quad(info["version"])
    WORK.mkdir(parents=True, exist_ok=True)
    target = WORK / "version_info.txt"
    target.write_text(
        VERSION_RESOURCE.format(
            quad=", ".join(str(part) for part in quad),
            author=info["author"],
            description=info["description"],
            copyright=f"\u00a9 {info['author']}",
            version=info["version"],
            exe=APP_EXE,
        ),
        encoding="utf-8",
    )
    return target


# ------------------------------------------------------------------- build #


def freeze(info: dict[str, str], resource: Path, console: bool) -> Path:
    """Run PyInstaller; return the folder holding the finished application."""
    environment = os.environ | {
        "DIAGRAM_MAKER_VERSION": info["version"],
        "DIAGRAM_MAKER_VERSION_FILE": str(resource),
        "DIAGRAM_MAKER_ICON": str(ICON),
        "DIAGRAM_MAKER_CONSOLE": "1" if console else "0",
    }
    say(f"freeze     PyInstaller -> {DIST.relative_to(ROOT)}\\{APP_DIR}")
    result = run(
        [
            sys.executable,
            "-m",
            "PyInstaller",
            "--noconfirm",
            "--clean",
            "--log-level=WARN",
            "--distpath",
            str(DIST),
            "--workpath",
            str(WORK / "pyinstaller"),
            str(SPEC),
        ],
        env=environment,
    )
    if result.returncode != 0:
        raise BuildError("PyInstaller failed; see the output above")
    bundle = DIST / APP_DIR
    if not bundle.is_dir():
        raise BuildError(f"PyInstaller reported success but {bundle} is not there")
    return bundle


def check_bundle(bundle: Path) -> list[str]:
    """The pieces a frozen build quietly loses without hooks."""
    wanted = {
        "the .exe": APP_EXE,
        # the window loads this at run time, so a missing copy means a blank
        # taskbar icon rather than a crash
        "the window icon": "icon.ico",
        # the icon is an .ico, so Qt needs its image plugin to read it
        "the .ico image plugin": "qico.dll",
        "QtWebEngineProcess.exe": "QtWebEngineProcess.exe",
        "the QtWebEngine resources": "qtwebengine_resources*.pak",
        "the QtWebEngine locales": "qtwebengine_locales/*.pak",
    }
    missing = [
        f"{label} ({pattern})"
        for label, pattern in wanted.items()
        if next(bundle.rglob(pattern), None) is None
    ]
    return missing


def export_check(bundle: Path) -> str | None:
    """The same .exe is a CLI, so make it write a diagram without a window."""
    target = WORK / "frozen-export.mmd"
    target.unlink(missing_ok=True)
    try:
        result = subprocess.run(
            [str(bundle / APP_EXE), "--export", str(target)],
            cwd=bundle,
            capture_output=True,
            timeout=120,
            check=False,
        )
    except OSError as error:
        if refused(error):
            raise BlockedByPolicy(str(error)) from error
        raise
    if result.returncode != 0:
        return f"--export exited with code {result.returncode}"
    if not target.is_file() or target.stat().st_size == 0:
        return "--export wrote no mermaid"
    return None


def launch_check(bundle: Path) -> str | None:
    """Start the frozen app offscreen; return why it died, or ``None``."""
    environment = os.environ | {
        "QT_QPA_PLATFORM": "offscreen",
        "QTWEBENGINE_CHROMIUM_FLAGS": "--no-sandbox --disable-gpu",
        "QT_LOGGING_RULES": "qt.webenginecontext.debug=false",
    }
    try:
        process = subprocess.Popen([str(bundle / APP_EXE)], cwd=bundle, env=environment)
    except OSError as error:
        if refused(error):
            raise BlockedByPolicy(str(error)) from error
        raise
    try:
        code = process.wait(timeout=GRACE_SECONDS)
    except subprocess.TimeoutExpired:
        # still running after the grace period: that is the pass condition
        subprocess.run(
            ["taskkill", "/F", "/T", "/PID", str(process.pid)],
            capture_output=True,
            check=False,
        )
        return None
    return f"it exited with code {code} after less than {GRACE_SECONDS:g}s"


# --------------------------------------------------------------- installer #


def find_iscc() -> Path | None:
    """Locate the Inno Setup command line compiler."""
    on_path = shutil.which("ISCC")
    if on_path:
        return Path(on_path)
    for variable, tail in (
        ("ProgramFiles(x86)", "Inno Setup 6"),
        ("ProgramFiles", "Inno Setup 6"),
        ("LOCALAPPDATA", "Programs/Inno Setup 6"),
    ):
        if root := os.environ.get(variable):
            candidate = Path(root) / tail / "ISCC.exe"
            if candidate.is_file():
                return candidate
    return None


def write_defines(info: dict[str, str], bundle: Path) -> Path:
    """Hand the installer script the paths and the version to stamp on it."""
    WORK.mkdir(parents=True, exist_ok=True)
    DEFINES.write_text(
        DEFINES_TEMPLATE.format(
            version=info["version"],
            bundle=bundle,
            out=DIST,
            icon=ICON,
        ),
        encoding="utf-8",
    )
    return DEFINES


def make_installer(info: dict[str, str], bundle: Path) -> Path | None:
    """Compile the setup program, or explain how to get Inno Setup."""
    iscc = find_iscc()
    if iscc is None:
        return None
    write_defines(info, bundle)
    say(f"installer  {iscc.name} -> DiagramMaker-{info['version']}-setup.exe")
    result = run([str(iscc), str(ISCC_SCRIPT)], capture_output=True, text=True)
    if result.returncode != 0:
        raise BuildError(f"Inno Setup failed:\n{result.stdout}\n{result.stderr}")
    setup = DIST / f"DiagramMaker-{info['version']}-setup.exe"
    if not setup.is_file():
        raise BuildError(f"Inno Setup reported success but {setup} is not there")
    return setup


def make_zip(info: dict[str, str]) -> Path:
    """A no-installer build, for people who would rather unpack and run."""
    say("portable   zipping the application folder")
    return Path(
        shutil.make_archive(
            str(DIST / f"DiagramMaker-{info['version']}-portable-x64"),
            "zip",
            root_dir=DIST,
            base_dir=APP_DIR,
        )
    )


# -------------------------------------------------------------------- main #


def parse_args(argv: list[str] | None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--skip-freeze",
        action="store_true",
        help="reuse the application already in dist/ instead of rebuilding it",
    )
    parser.add_argument(
        "--console",
        action="store_true",
        help="build with a console window, for debugging a frozen build",
    )
    parser.add_argument(
        "--icon", action="store_true", help="redraw packaging/icon.ico first"
    )
    parser.add_argument(
        "--no-run", action="store_true", help="skip the offscreen launch check"
    )
    parser.add_argument(
        "--zip", action="store_true", help="always write the portable zip too"
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    arguments = parse_args(argv)
    if sys.platform != "win32":
        say("this script builds a Windows installer; run it on Windows")
        return 2
    if importlib.util.find_spec("PyInstaller") is None:
        say("PyInstaller is missing. It lives in the packaging extra:")
        say("    uv sync --extra packaging")
        return 2

    info = metadata()
    say(f"Diagram Maker {info['version']}")
    checks_skipped = arguments.no_run
    try:
        ensure_icon(arguments.icon)
        resource = write_version_resource(info)

        bundle = DIST / APP_DIR
        if arguments.skip_freeze:
            if not (bundle / APP_EXE).is_file():
                raise BuildError(f"no frozen application in {bundle} to reuse")
            say("freeze     skipped, reusing dist/")
        else:
            bundle = freeze(info, resource, arguments.console)

        if missing := check_bundle(bundle):
            raise BuildError(
                "the bundle is incomplete - PyInstaller left out:\n  "
                + "\n  ".join(missing)
            )
        files = [item for item in bundle.rglob("*") if item.is_file()]
        say(f"bundle     {len(files)} files, {sum(f.stat().st_size for f in files) / 1_048_576:.0f} MB")

        if arguments.no_run:
            say("checks     offscreen launch and headless export skipped")
        else:
            try:
                if reason := export_check(bundle):
                    raise BuildError(f"the frozen application cannot export: {reason}")
                say("cli        --export wrote a diagram")
                if reason := launch_check(bundle):
                    raise BuildError(
                        f"the frozen application did not stay up: {reason}\n"
                        "rebuild with --console to see what it printed"
                    )
                say(f"launch     still running after {GRACE_SECONDS:g}s offscreen")
            except BlockedByPolicy as refusal:
                # an application control policy is not something the build can
                # fix, and the installer is still worth having
                say(f"checks     Windows refused to start the app: {refusal}")
                say("           Smart App Control blocks programs it has not seen")
                say("           before, and every build writes a new one. Sign the")
                say("           binaries, or run the checks where it allows them.")
                checks_skipped = True

        setup = make_installer(info, bundle)
        if setup is None:
            say(INNO_HINT)
            say(f"portable   {make_zip(info)}")
        else:
            say(f"installer  {setup}  ({setup.stat().st_size / 1_048_576:.1f} MB)")
            if arguments.zip:
                say(f"portable   {make_zip(info)}")
        if checks_skipped:
            say("note       the build was not started here, so it is unverified")
    except BuildError as error:
        say(f"error: {error}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
